
<?php 

<footer>
        &copy; Ed Watkins - s3490783 | Grace Geddes - s3485536 - RMIT - 2014 | 
        <a href="http://validator.w3.org/check?uri=referer">
        <img style="height:25px" src="http://www.w3.org/html/logo/downloads/HTML5_Logo_32.png" alt="HTML Validator" /></a> 
        <a href="http://jigsaw.w3.org/css-validator/check/referer">
        <img style="height:25px" src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="CSS Validator"/></a>  
</footer>

?>